### PR TITLE
fix(package.json): edit main, exports and publishConfig to improve DX

### PR DESCRIPTION
**Pull request by manudeli**
# Edit main, exports and publishConfig to improve DX

## Cannot find module directly, if contributors didn't build packages.
image
Though there is built packages, Contributor want to access source itself, not built package.

## Solution I thought
How about making vscode access to workspaces source code directly, not built package. if package.json using publishConfig, making built package and developing package in workspaces for DX separately is available.
```json
{
  "main": "src/index.ts",
  "exports": {
    ".": {
      "require": "./src/index.ts",
      "import": "./src/index.ts"
    },
    "./package.json": "./package.json"
  },
  "publishConfig": {
    "access": "public",
    "exports": {
      ".": {
        "require": "./dist/index.js",
        "import": "./esm/index.mjs",
        "types": "./dist/index.d.ts"
      },
      "./package.json": "./package.json"
    },
    "import": "./esm/index.mjs",
    "main": "./dist/index.js",
    "types": "dist/index.d.ts",
    "module": "esm/index.mjs"
  },
}
```

### CODE REVIEW

**Review by SoYoung210 — COMMENTED** [review]
Thanks for Contribute.

I would appreciate it if you could change the **order of the exports fields(types first)** by referring to below information. 👇 
https://github.com/microsoft/TypeScript/issues/46334 

cc @JaeYeopHan

**Comment by manudeli** [comment]
> Thanks for Contribute.
> 
> I would appreciate it if you could change the **order of the exports fields(types first)** by referring to below information. 👇 [microsoft/TypeScript#46334](https://github.com/microsoft/TypeScript/issues/46334)
> 
> cc @JaeYeopHan

after trying to reproduce problem situation. but actually, I couldn't reproduce it what you worried. 

Anyway, I changed order of exports as your link reference's advice, but I couldn't get confidence at this implementation. If my change is wrong, could you make some code for me? I just want to know what you want exactly.

**Comment by SoYoung210** [comment]
I don't know how you tried it, but as written in the issue above, in an environment using (ts)`module: next` and wrong order of the exports map - `types` are not described first, **the type evaluation can match the wrong file**.

btw, i'll investigate broken netlify issues...  I don't think it's because of this change 🤔, but can you wait a moment? 🙏  🙏

**Comment by SoYoung210** [comment]
@manudeli netlify issue is solved in #231. I'll rebase this PR and publish beta release for testing.

**Comment by SoYoung210** [comment]
@manudeli sorry i cant rebase this pr (this pr is created through a forked repo 😅)
can u do it?

**Comment by manudeli** [comment]
@JaeYeopHan @SoYoung210 Rebasing done

**Review by SoYoung210 — APPROVED** [review]

**Pull request merged**
