### PR TITLE
chore: rename the variable 'weekendDays' to 'weekDays'

### PR DESCRIPTION
**Pull request by jaehunn**

### CODE REVIEW

**Comment by JaeYeopHan** [comment]
why is this change necessary?

**Comment by jaehunn** [comment]
sorry, I didn't write an explanation why I changed it.

my understanding is that 'weekendDays' mean to Saturday and Sunday .
the usage (useCalendar.tsx line.33) showed that it was already using 'weekDays' the number of days in a week.

**Comment by jaehunn** [comment]
please le me know, if i my understanding is not the same with the intent of the code. thank you

**Comment by JaeYeopHan** [comment]
> my understanding is that 'weekendDays' mean to Saturday and Sunday .

omg you're right!!

**Review by JaeYeopHan — APPROVED** [review]

**Comment by JaeYeopHan** [comment]
@all-contributors please add @jaehunn for maintenance

**Pull request merged**
